// import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { KeyboardNav } from "../components/keyboard";
import { cn } from "@/lib/utils";
import { ContentWrapper } from "@/components/page.transition";
import { LayoutContent } from "@/components/layout.content";
import { TitleProvider, useTitle } from "@/context/title.provide";

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "dark", "antialiased", geistSans.variable, geistMono.variable, "font-mono", jetbrainsMono.variable)}
    >
      <body className="m-0 min-h-full bg-black flex flex-col">
        <TitleProvider>
          <LayoutContent>{children}</LayoutContent>
        </TitleProvider>
      </body>
    </html>
  );
}

